_id: 03b649a0-bb61-11e8-89fb-bde33cd2d3fe
quote: >-
  Thanks for the guide, seems interesting. Will try to add this to my personal
  site. Trying to get away from WordPress
name: Hamilton
hidden: ''
date: '2018-09-18T16:36:38.774Z'
